### ISSUE TITLE
Single builtin node exec without fork.

### ISSUE THREAD

**Issue by Le-Technologue** [Le-Technologue/minishell#16]
Crucial to make "cd" work, since chdir just affects the process it's run into.

**Comment by Devexia** [comment]
I think we should manage this in exec, not doing any fork if the cmd is a single builtin

**Comment by Le-Technologue** [comment]
A conditional check of shell->mainline->entries value is the ticket then.

**Comment by Devexia** [comment]
We need to investigate if this check's only relevant because of cd or for other builtins too?

**Comment by Devexia** [comment]
> 

Investigations masterfully conducted : If any builtin is alone, we don't fork. We do otherwise

**Comment by Le-Technologue** [comment]
@Devexia, seems like 6535066598ed3eb6da7d6af9167be2066965c67d this is a poor idea, try to do `echo pi > ka` and it will print "pi" on the screen, instead of redirecting its output to the file "ka". Putting back that check prevents it from printing 'pi' on screen, but it still isn't writing anything to file"ka" tho.

**Comment by Le-Technologue** [comment]
I've been debugging and when you dup FDs in forks they just affect this fork right ( #26 ) ?

So when you launch cat -e alone, it should read from STDIN... since you can't type into your forked process STDIN, it'll at best scramble lightly your parent process input while still not getting anything usable in its own process .

Then :
- Any command receiving STDIN input should receive it from the PARENT process or we can't type shit in it.
- FD sharing should be thought according the data in issue #26

**Comment by Le-Technologue** [comment]
3a1712345a8ff7dd136282cb4b5df5fd9f8884c0 achieved the idea from 132946de053d02cc50f06badb72f4cfee6ff6342 everything seems in order.
