### ISSUE TITLE
Dealing with ctrl-D

### ISSUE THREAD

**Issue by yaakoub-berkat** [Le-Technologue/minishell#20]
To handle the ctrl-C and ctrl-\, we can use signals and signal handlers (ctrl-C stands for SIGINT and ctrl-D stands for SIGQUIT).
To handle ctrl-D which stands for EOF (no signal assigned to it), we need to deal with it when parsing and call do_exit function to exit the shell.
@Le-Technologue, I hope i explained the issue well !

**Comment by Le-Technologue** [comment]
So I'm supposed to retrieve an EOF and interpret it, I'll look into it.

**Comment by Le-Technologue** [comment]
So @yaakoub-berkat it's not a character and while parsing I only deal with those, what the heck ? https://ruslanspivak.com/eofnotchar/

**Comment by Le-Technologue** [comment]
If I get the idea up there @yaakoub-berkat , readline() will return -1 upon reaching EOF. As does read(), so there is your interruption! I'll check that out if you don't before me, but first I have to finish my parsing fix.

**Comment by Le-Technologue** [comment]
![image](https://user-images.githubusercontent.com/73589177/155106545-f59f8db3-d430-40d8-968e-239d3739a0c8.png)

**Comment by Le-Technologue** [comment]
It seems too easy but it works d7ecaefad1e9fc5f2b21b8c4f50acbd560c5fc6e
