### ISSUE TITLE
Signal handling in forks

### ISSUE THREAD

**Issue by Le-Technologue** [Le-Technologue/minishell#33]
Apparently you are supposed to cut signal reception in the forked program to avoid confusion. @yaakoub-berkat ur the signal man, do you have an idea ?

**Comment by yaakoub-berkat** [comment]
This is supposedly done but not yet tested, so we might have to adapt the code.
For the parent process, it's tested and it works !

**Comment by Le-Technologue** [comment]
f94ea540a8e6badf3b0697617261fc3458495590 seems to seal the deal !
