### ISSUE TITLE
I followed a correction pdf and here are the issues I got out of it

### ISSUE THREAD

**Issue by Devexia** [Le-Technologue/minishell#42]
- The shell segfaults when we give him a $ followed by something that isn't an env var

- Using unset to remove an env variable produces some weird bugs : We can't use env afterwards to display, and using export crashes the shell. (they both work well without unset tho)

- "cat | cat | ls" doesn't behave like bash. Seems like some more pipe headaches -_- (to be fair even Heb didn't handle this well so let's maybe put that aside? Je garde ça dans un coin de ma tête tho..)

Parts of the pdf I didn't test :
Hdocs (not fully implemented)
Redirections (not feeling confident with every use case, looks solid from the little tests I've tried tho)

Hf m8, have a cool morning✌️ I'll be seeing u soon

**Comment by Devexia** [comment]
Everything else is working wonders tho, let's keep our heads up and crush this mofo

**Comment by Devexia** [comment]
#42 🥳

**Comment by Le-Technologue** [comment]
> #42 partying_face

That's why it was a clusterfuck to fix it... #IHTFP but in the end 88f5e2cabffba9535a23f62165f4a8227d1e0b9b should do the trick for expand vars !
