### ISSUE TITLE
Redirs + pipes

### ISSUE THREAD

**Issue by Devexia** [Le-Technologue/minishell#45]
Using piped command and redirecting output leaves an fd open and messes up input and the flow of the shell.
I'm currently investigating this and putting this issue as to not forget
echo jaaj | cat > outfile

**Comment by Devexia** [comment]
It seems to open up a prompt like when we put a pipe but no commands afterwards.
I'm wondering if the problem comes from exec or not 🤔

**Comment by Devexia** [comment]
Scratched my head a lot to try and fix this. We should look into disabling the thing that opens up a prompt if a ' | ' has no follow up

**Comment by Le-Technologue** [comment]
Fixed here : a5af05b94e1ce6b3afcc15a56721ff35ab159caa
